package com.atiurin.espressopageobject.core.espresso.resultanalyzer

import com.atiurin.espressopageobject.core.common.OperationResultAnalyzer

interface EspressoOperationResultAnalyzer : OperationResultAnalyzer