name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests_on_api_21:
    runs-on: macos-latest
    strategy:
      matrix: 
        api_level: [21, 22, 23, 24, 25, 26, 27, 28, 29]
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run ui tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        script: ./gradlew :app:connectedCheck --stacktrace
        profile: Nexus 6
